### ISSUE TITLE
cannot import name 'get_image_splitter' from 'image_splitter'

### ISSUE THREAD

**Issue by metawizard** [s-smits/ui-screenshot-to-prompt#1]
File "/workspaces/ui-screenshot-to-prompt/src/ui-screenshot-to-prompt/main.py", line 25, in <module>
    from image_splitter import get_image_splitter
ImportError: cannot import name 'get_image_splitter' from 'image_splitter' (/home/codespace/.cache/pypoetry/virtualenvs/ui-screenshot-to-prompt-h24N18tO-py3.12/lib/python3.12/site-packages/image_splitter/__init__.py). Did you mean: 'image_splitter'?

I've run into this issue trying to run it in multiple environments(Github workspace, Replit, local). Any suggestions how to resolve?

**Comment by s-smits** [comment]
Thank you for trying it in multiple environments, I should've tested more rigorously (tests coming up next version).
I've updated to 0.3.0, could you try cloning and running the repo again?

**Comment by s-smits** [comment]
Can I close this?

**Comment by metawizard** [comment]
Could be closed now.
The only remaining problem I had was replacing model="claude-3-sonnet-latest" with other model or using openrouter.

**Comment by s-smits** [comment]
Will fix that in the next update.
